export { default as blackHeartIcon } from "./blackHeartIcon.svg";
export { default as drinkIcon } from "./drinkIcon.svg";
export { default as glassIcon } from "./glassIcon.svg";
export { default as mealIcon } from "./mealIcon.svg";
export { default as profileIcon } from "./profileIcon.svg";
export { default as searchIcon } from "./searchIcon.svg";
export { default as shareIcon } from "./shareIcon.svg";
export { default as whiteHeartIcon } from "./whiteHeartIcon.svg";
export { default as recipeIcon } from "./recipeIcon.svg";
